-- VSCode & other IDEs can auto complete based on usage of text
-- So this file provides autocompletion through that
-- Otherwise you can sort of use this as an API reference? Who knows...

-- Base
Neoprisma

-- Keyboard
Neoprisma.Keyboard
Neoprisma.Keyboard.onKeyPress
Neoprisma.Keyboard.onKeyRelease
Neoprisma.Keyboard.keyStatus

-- Keys
Neoprisma.Keys
Neoprisma.Keys.kVK_ANSI_A
Neoprisma.Keys.kVK_ANSI_S
Neoprisma.Keys.kVK_ANSI_D
Neoprisma.Keys.kVK_ANSI_F
Neoprisma.Keys.kVK_ANSI_H
Neoprisma.Keys.kVK_ANSI_G
Neoprisma.Keys.kVK_ANSI_Z
Neoprisma.Keys.kVK_ANSI_X
Neoprisma.Keys.kVK_ANSI_C
Neoprisma.Keys.kVK_ANSI_V
Neoprisma.Keys.kVK_ANSI_B
Neoprisma.Keys.kVK_ANSI_Q
Neoprisma.Keys.kVK_ANSI_W
Neoprisma.Keys.kVK_ANSI_E
Neoprisma.Keys.kVK_ANSI_R
Neoprisma.Keys.kVK_ANSI_Y
Neoprisma.Keys.kVK_ANSI_T
Neoprisma.Keys.kVK_ANSI_1
Neoprisma.Keys.kVK_ANSI_2
Neoprisma.Keys.kVK_ANSI_3
Neoprisma.Keys.kVK_ANSI_4
Neoprisma.Keys.kVK_ANSI_6
Neoprisma.Keys.kVK_ANSI_5
Neoprisma.Keys.kVK_ANSI_Equal
Neoprisma.Keys.kVK_ANSI_9
Neoprisma.Keys.kVK_ANSI_7
Neoprisma.Keys.kVK_ANSI_Minus
Neoprisma.Keys.kVK_ANSI_8
Neoprisma.Keys.kVK_ANSI_0
Neoprisma.Keys.kVK_ANSI_RightBracket
Neoprisma.Keys.kVK_ANSI_O
Neoprisma.Keys.kVK_ANSI_U
Neoprisma.Keys.kVK_ANSI_LeftBracket
Neoprisma.Keys.kVK_ANSI_I
Neoprisma.Keys.kVK_ANSI_P
Neoprisma.Keys.kVK_ANSI_L
Neoprisma.Keys.kVK_ANSI_J
Neoprisma.Keys.kVK_ANSI_Quote
Neoprisma.Keys.kVK_ANSI_K
Neoprisma.Keys.kVK_ANSI_Semicolon
Neoprisma.Keys.kVK_ANSI_Backslash
Neoprisma.Keys.kVK_ANSI_Comma
Neoprisma.Keys.kVK_ANSI_Slash
Neoprisma.Keys.kVK_ANSI_N
Neoprisma.Keys.kVK_ANSI_M
Neoprisma.Keys.kVK_ANSI_Period
Neoprisma.Keys.kVK_ANSI_Grave
Neoprisma.Keys.kVK_ANSI_KeypadDecimal
Neoprisma.Keys.kVK_ANSI_KeypadMultiply
Neoprisma.Keys.kVK_ANSI_KeypadPlus
Neoprisma.Keys.kVK_ANSI_KeypadClear
Neoprisma.Keys.kVK_ANSI_KeypadDivide
Neoprisma.Keys.kVK_ANSI_KeypadEnter
Neoprisma.Keys.kVK_ANSI_KeypadMinus
Neoprisma.Keys.kVK_ANSI_KeypadEquals
Neoprisma.Keys.kVK_ANSI_Keypad0
Neoprisma.Keys.kVK_ANSI_Keypad1
Neoprisma.Keys.kVK_ANSI_Keypad2
Neoprisma.Keys.kVK_ANSI_Keypad3
Neoprisma.Keys.kVK_ANSI_Keypad4
Neoprisma.Keys.kVK_ANSI_Keypad5
Neoprisma.Keys.kVK_ANSI_Keypad6
Neoprisma.Keys.kVK_ANSI_Keypad7
Neoprisma.Keys.kVK_ANSI_Keypad8
Neoprisma.Keys.kVK_ANSI_Keypad9
Neoprisma.Keys.kVK_Return
Neoprisma.Keys.kVK_Tab
Neoprisma.Keys.kVK_Space
Neoprisma.Keys.kVK_Delete
Neoprisma.Keys.kVK_Escape
Neoprisma.Keys.kVK_Command
Neoprisma.Keys.kVK_Shift
Neoprisma.Keys.kVK_CapsLock
Neoprisma.Keys.kVK_Option
Neoprisma.Keys.kVK_Control
Neoprisma.Keys.kVK_RightCommand
Neoprisma.Keys.kVK_RightShift
Neoprisma.Keys.kVK_RightOption
Neoprisma.Keys.kVK_RightControl
Neoprisma.Keys.kVK_Function
Neoprisma.Keys.kVK_F17
Neoprisma.Keys.kVK_VolumeUp
Neoprisma.Keys.kVK_VolumeDown
Neoprisma.Keys.kVK_Mute
Neoprisma.Keys.kVK_F18
Neoprisma.Keys.kVK_F19
Neoprisma.Keys.kVK_F20
Neoprisma.Keys.kVK_F5
Neoprisma.Keys.kVK_F6
Neoprisma.Keys.kVK_F7
Neoprisma.Keys.kVK_F3
Neoprisma.Keys.kVK_F8
Neoprisma.Keys.kVK_F9
Neoprisma.Keys.kVK_F11
Neoprisma.Keys.kVK_F13
Neoprisma.Keys.kVK_F16
Neoprisma.Keys.kVK_F14
Neoprisma.Keys.kVK_F10
Neoprisma.Keys.kVK_ContextualMenu
Neoprisma.Keys.kVK_F12
Neoprisma.Keys.kVK_F15
Neoprisma.Keys.kVK_Help
Neoprisma.Keys.kVK_Home
Neoprisma.Keys.kVK_PageUp
Neoprisma.Keys.kVK_ForwardDelete
Neoprisma.Keys.kVK_F4
Neoprisma.Keys.kVK_End
Neoprisma.Keys.kVK_F2
Neoprisma.Keys.kVK_PageDown
Neoprisma.Keys.kVK_F1
Neoprisma.Keys.kVK_LeftArrow
Neoprisma.Keys.kVK_RightArrow
Neoprisma.Keys.kVK_DownArrow
Neoprisma.Keys.kVK_UpArrow
Neoprisma.Keys.kVK_ISO_Section
Neoprisma.Keys.kVK_JIS_Yen
Neoprisma.Keys.kVK_JIS_Underscore
Neoprisma.Keys.kVK_JIS_KeypadComma
Neoprisma.Keys.kVK_JIS_Eisu
Neoprisma.Keys.kVK_JIS_Kana

-- Mouse
Neoprisma.Mouse
Neoprisma.Mouse.onMouseDown
Neoprisma.Mouse.onMouseUp
Neoprisma.Mouse.onMouseMove
Neoprisma.Mouse.onMouseScroll
Neoprisma.Mouse.moveMouseAbsolute
Neoprisma.Mouse.warpMouseAbsolute
Neoprisma.Mouse.dragMouseAbsolute
Neoprisma.Mouse.mouseButtonStatus
Neoprisma.Mouse.mouseScroll

-- Clock
Neoprisma.Clock
Neoprisma.Clock.time
Neoprisma.Clock.sleep
